server:
  port: 7000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.21.43:3306/construction?serverTimezone=UTC&useSSL=true
    username: construction
    password: construction
  thymeleaf:
    prefix: classpath:/templates/ # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
  servlet:
    multipart:
      max-file-size: 30MB #SpringBoot默认上传文件大小不能超过1MB
      max-request-size: 30MB

  redis:
    database: 0  # 数据库，默认为0
    host: localhost # redis的ip地址
    port: 6379 # 端口号
    password:  # 如果有密码
    timeout: 5000
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 100000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.bwsk.entity

logging:
  level:
    com.bwsk: DEBUG
  file:
    path: ./logs

